trigger:
- master

pool:
  dva-self-hosted: vmdvadagntsnd01

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'snd-registry'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks-mpi-snd-svc'
    namespace: 'mpi-snd'
    command: 'apply'
    arguments: '-f deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'