trigger:
- master

pool:
  dva-self-hosted: vmdvadagntsnd01

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'snd-registry'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'new-uat-test'
    azureResourceGroup: 'rg-azr-dva-aks-uat-001'
    kubernetesCluster: 'aks-azr-dva-uat-001'
    namespace: 'mpi-uat'
    command: 'apply'
    arguments: '-f deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'