trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-connection'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'kyndryl-test'
    azureResourceGroup: 'rg-azr-dva-aks-snd-001'
    kubernetesCluster: 'aks-azr-dva-snd-001'
    namespace: 'mpi-snd'
    command: 'apply'
    arguments: '-f deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'