apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: acrazrdvasnd001.azurecr.io/nginx-echo-headers:latest
  imagePullSecrets:
  - name: acrcred
  nodeSelector:
    "beta.kubernetes.io/os": linux
